const WaqtiCore=(()=>{const KEY='waqti_v2_data';const prayerNames=['المغرب','العشاء','الفجر','الظهر','العصر'];const defaults={version:2,settings:{lat:30.0444,lng:31.2357},actions:[{id:'a_sleep',name:'نوم وراحة',color:'#eadfd4'},{id:'a_work',name:'عمل',color:'#dce9f6'},{id:'a_quran',name:'قرآن وتعلّم',color:'#e1efdd'},{id:'a_family',name:'وقت الأسرة',color:'#f2e3ef'}],recurringTasks:[],dayOverrides:{},days:{}};function clone(v){return JSON.parse(JSON.stringify(v))}function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return normalize(x||clone(defaults))}catch{return clone(defaults)}}function save(d){ActionCategories.normalize(d);localStorage.setItem(KEY,JSON.stringify(d));window.dispatchEvent(new CustomEvent('waqti:changed',{detail:d}))}function normalize(d){d={...clone(defaults),...d};d.settings={...defaults.settings,...(d.settings||{})};d.actions=Array.isArray(d.actions)?d.actions:clone(defaults.actions);d.recurringTasks=Array.isArray(d.recurringTasks)?d.recurringTasks:[];d.dayOverrides=d.dayOverrides||{};d.days=d.days||{};ActionCategories.normalize(d);return d}function id(prefix='id'){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}function dateKey(dt){const d=new Date(dt);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}function ensureDay(d,k){if(!d.days[k])d.days[k]={slots:Array.from({length:96},()=>({actual:null,planned:null})),prayerTasks:{}};if(!Array.isArray(d.days[k].slots)||d.days[k].slots.length!==96)d.days[k].slots=Array.from({length:96},(_,i)=>d.days[k].slots?.[i]||{actual:null,planned:null});prayerNames.forEach(p=>{if(!Array.isArray(d.days[k].prayerTasks[p]))d.days[k].prayerTasks[p]=[]});return d.days[k]}function weekday(k){return new Date(k+'T12:00:00').getDay()}function recurringApplies(r,k,p){if(r.active===false)return false;if(r.prayer!==p)return false;if(r.startDate&&k<r.startDate)return false;if(r.endDate&&k>r.endDate)return false;if(Array.isArray(r.days)&&r.days.length&& !r.days.includes(weekday(k)))return false;return true}function hydrateRecurring(d,k){const day=ensureDay(d,k);for(const p of prayerNames){const existing=day.prayerTasks[p];for(const r of d.recurringTasks.filter(x=>recurringApplies(x,k,p))){const overridden=d.dayOverrides[k]?.[r.id];if(overridden)continue;if(!existing.some(t=>t.recurringId===r.id)){existing.push({id:id('pt'),title:r.title,status:'pending',recurringId:r.id,linked:true})}}}return day}function detachTask(d,k,p,taskId,newTitle){const day=hydrateRecurring(d,k);const t=day.prayerTasks[p].find(x=>x.id===taskId);if(!t)return false;if(t.recurringId&&t.linked!==false){d.dayOverrides[k]=d.dayOverrides[k]||{};d.dayOverrides[k][t.recurringId]=true;t.recurringId=null;t.linked=false}t.title=newTitle;return true}function updateRecurring(d,rid,patch){
const r=d.recurringTasks.find(x=>x.id===rid);if(!r)return false;
const next={...r,...patch};if(!next.title?.trim()||!prayerNames.includes(next.prayer))return false;
if(!Array.isArray(next.days)||!next.days.every(n=>Number.isInteger(n)&&n>=0&&n<=6))return false;
Object.assign(r,next,{title:next.title.trim()});
for(const k of Object.keys(d.days)){
const day=ensureDay(d,k);let linked=[];
for(const p of prayerNames){linked.push(...day.prayerTasks[p].filter(t=>t.recurringId===rid&&t.linked!==false));day.prayerTasks[p]=day.prayerTasks[p].filter(t=>!(t.recurringId===rid&&t.linked!==false))}
if(recurringApplies(r,k,r.prayer)&&!d.dayOverrides[k]?.[rid]){
const t=linked[0]||{id:id('pt'),status:'pending',recurringId:rid,linked:true};t.title=r.title;day.prayerTasks[r.prayer].push(t)
}
}
return true}
return{KEY,prayerNames,defaults,load,save,clone,id,dateKey,ensureDay,hydrateRecurring,detachTask,updateRecurring,weekday}})();