/* Uses the same daily occurrences and persistence as the day view. */
let taskFilters={query:'',prayer:'all',status:'all',kind:'all'};
function dashboardTasks(){
 const d=day(),weekday=new Date(date+'T12:00:00').getDay();
 return [...d.tasks,...state.repeat.filter(t=>t.days.includes(weekday)&&!d.excludedRepeat?.[t.id]).map(t=>({...t,recurrent:true}))];
}
function taskStatus(t){return day().done[t.id]?'done':day().failed?.[t.id]?'failed':'pending'}
function renderDashboard(){
 const all=dashboardTasks(),done=all.filter(t=>taskStatus(t)==='done').length,failed=all.filter(t=>taskStatus(t)==='failed').length;
 app.innerHTML=`<div class="top"><div><h1>لوحة المهام</h1><p>كل مهام يومك، في مكان واحد.</p></div><div class="date"><button data-dashboard-shift="-1" aria-label="اليوم السابق">→</button><input id="dashboardDate" type="date" value="${date}" aria-label="تاريخ نهار اليوم المختار"><button data-dashboard-shift="1" aria-label="اليوم التالي">←</button><button id="dashboardToday">اليوم</button></div></div>
 <div class="hero"><div><h2>${hijriLabel(date)}</h2><p>${dayRangeLabel()}</p><span>إنجاز مهام اليوم: ${all.length?Math.round(done/all.length*100):0}٪</span><progress class="task-progress" value="${done}" max="${all.length||1}" aria-label="نسبة إنجاز المهام"></progress></div><button id="dashboardRepeat" class="secondary">↻ إدارة المهام المتكررة</button></div>
 <div class="dashboard-stats">${[['all','كل المهام',all.length],['pending','بانتظار التنفيذ',all.length-done-failed],['done','تمت',done],['failed','لم أفعلها',failed]].map(([value,label,count])=>`<button class="panel dashboard-stat" data-dashboard-status="${value}" aria-pressed="${taskFilters.status===value}"><span>${label}</span><strong>${count}</strong></button>`).join('')}</div>
 <section class="panel"><h2>إضافة مهمة لليوم المختار</h2><form id="dashboardAdd" class="form"><label class="field dashboard-name">المهمة<input name="name" required maxlength="150" placeholder="ما الذي تريد إنجازه؟"></label><label class="field">فترة الصلاة<select name="prayer">${prayerOrder.map(i=>`<option value="${i}" ${i===prayer?'selected':''}>${names[i]}</option>`).join('')}</select></label><button class="primary">إضافة المهمة</button></form></section>
 <section class="panel"><div class="panel-title"><h2>مهام اليوم</h2><span id="dashboardCount" class="badge"></span></div><div class="dashboard-filters"><label class="field">بحث<input id="taskSearch" type="search" maxlength="150" value="${esc(taskFilters.query)}" placeholder="ابحث باسم المهمة"></label><label class="field">الفترة<select id="taskPrayer"><option value="all">كل الفترات</option>${prayerOrder.map(i=>`<option value="${i}">${names[i]}</option>`).join('')}</select></label><label class="field">الحالة<select id="taskStatus"><option value="all">كل الحالات</option><option value="pending">بانتظار التنفيذ</option><option value="done">تمت</option><option value="failed">لم أفعلها</option></select></label><label class="field">النوع<select id="taskKind"><option value="all">كل المهام</option><option value="single">مستقلة</option><option value="repeat">متكررة مرتبطة</option></select></label></div><div id="dashboardList"></div><p class="hint">الإحصاءات لمهام اليوم كله دون قوائم الصلاة الثابتة. اضغط علامة الحالة مجددًا لإلغائها. تعديل أو حذف مهمة متكررة هنا يؤثر على هذا اليوم فقط.</p></section>`;
 $('#dashboardDate').onchange=e=>{if(e.target.value)goDay(e.target.value,false)};
 $('#dashboardToday').onclick=()=>goDay(activeDay(),true);
 app.querySelectorAll('[data-dashboard-shift]').forEach(b=>b.onclick=()=>goDay(addDate(date,+b.dataset.dashboardShift),false));
 $('#dashboardRepeat').onclick=()=>{view='repeat';render()};
 app.querySelectorAll('[data-dashboard-status]').forEach(b=>b.onclick=()=>{taskFilters.status=b.dataset.dashboardStatus;render()});
 $('#dashboardAdd').onsubmit=e=>{e.preventDefault();const name=e.target.elements.name.value.trim();if(!name)return;day().tasks.push({id:uid(),name,prayer:+e.target.elements.prayer.value});save();render();toast('تمت إضافة المهمة')};
 for(const [id,key] of [['taskPrayer','prayer'],['taskStatus','status'],['taskKind','kind']]){$('#'+id).value=taskFilters[key];$('#'+id).onchange=e=>{taskFilters[key]=e.target.value;renderDashboardList()}};
 $('#taskSearch').oninput=e=>{taskFilters.query=e.target.value;renderDashboardList()};
 renderDashboardList();
}
function renderDashboardList(){
 const all=dashboardTasks(),filtered=all.filter(t=>(!taskFilters.query||t.name.toLocaleLowerCase().includes(taskFilters.query.trim().toLocaleLowerCase()))&&(taskFilters.prayer==='all'||t.prayer===+taskFilters.prayer)&&(taskFilters.status==='all'||taskStatus(t)===taskFilters.status)&&(taskFilters.kind==='all'||(taskFilters.kind==='repeat'?t.recurrent:!t.recurrent)));
 $('#dashboardCount').textContent=`${filtered.length} من ${all.length}`;
 app.querySelectorAll('[data-dashboard-status]').forEach(b=>b.setAttribute('aria-pressed',String(taskFilters.status===b.dataset.dashboardStatus)));
 $('#dashboardList').innerHTML=filtered.length?prayerOrder.map(p=>{const group=filtered.filter(t=>t.prayer===p);return group.length?`<section class="dashboard-group"><h3>${names[p]} <span class="badge">${group.length}</span></h3>${group.map(t=>`<div class="taskrow ${taskStatus(t)==='done'?'done':taskStatus(t)==='failed'?'missed':''}"><span>${esc(t.name)}<small>${t.recurrent?'↻ متكررة مرتبطة':t.detachedFrom?'مستقلة لهذا اليوم':'مهمة يومية'} · ${{done:'تمت',failed:'لم أفعلها',pending:'بانتظار التنفيذ'}[taskStatus(t)]}</small></span><div class="task-controls"><button class="status-button ${taskStatus(t)==='done'?'yes':''}" data-dash-done="${esc(t.id)}" aria-label="تمت: ${esc(t.name)}" aria-pressed="${taskStatus(t)==='done'}">✓</button><button class="status-button ${taskStatus(t)==='failed'?'no':''}" data-dash-failed="${esc(t.id)}" aria-label="لم أفعلها: ${esc(t.name)}" aria-pressed="${taskStatus(t)==='failed'}">✕</button><button data-dash-edit="${esc(t.id)}">تعديل</button><button class="danger" data-dash-delete="${esc(t.id)}">حذف</button></div></div>`).join('')}</section>`:''}).join(''):`<p class="empty-note">${all.length?'لا توجد مهام تطابق البحث والتصفية.':'لا توجد مهام لهذا اليوم. أضف أول مهمة من النموذج أعلاه.'}</p>`;
 for(const status of ['done','failed'])app.querySelectorAll(`[data-dash-${status}]`).forEach(b=>b.onclick=()=>{setTaskOutcome(day(),b.getAttribute('data-dash-'+status),status);save();render()});
 app.querySelectorAll('[data-dash-edit]').forEach(b=>b.onclick=()=>openTaskEditor(all.find(t=>t.id===b.dataset.dashEdit)));
 app.querySelectorAll('[data-dash-delete]').forEach(b=>b.onclick=()=>{const t=all.find(t=>t.id===b.dataset.dashDelete);if(!t||!confirm('حذف المهمة من هذا اليوم فقط؟'))return;const d=day();if(t.recurrent)(d.excludedRepeat??={})[t.id]=true;else d.tasks=d.tasks.filter(x=>x.id!==t.id);delete d.done[t.id];if(d.failed)delete d.failed[t.id];save();render()});
}
