/* Slot notes and half-open quarter-hour ranges. */
const SlotTools=(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function validate(start,end,first){if(!Number.isInteger(start)||!Number.isInteger(end)||start<first||end>first+96||end<=start)throw Error('اختر وقت نهاية بعد البداية داخل هذا اليوم.');}
function apply(day,start,end,kind,action,note,first=0,array=false){validate(start,end,first);if(!['actual','planned'].includes(kind)||typeof note!=='string'||note.length>1000)throw Error('بيانات غير صالحة');note=note.trim();for(let n=start;n<end;n++){const i=((n%96)+96)%96;if(array){const s=day.slots[i];s[kind]=action||null;s[kind+'Note']=note;}else{const actions=kind==='actual'?day.slots:(day.planned??={}),notes=(day[kind+'Notes']??={});if(action)actions[i]=action;else delete actions[i];if(note)notes[i]=note;else delete notes[i];}}}
function open(o){const q=s=>document.querySelector(s),first=o.first,last=first+96;let selected=o.action||'';
const options=(from,to,value)=>Array.from({length:to-from+1},(_,j)=>{let n=from+j;return `<option value="${n}" ${n===value?'selected':''}>${esc(o.time(n))}${n===last?' · نهاية اليوم':''}</option>`}).join('');
const groups=[];for(const c of o.categories||[])groups.push({id:c.id,name:c.name,description:c.description,color:c.color,actions:[]});
for(const a of o.actions){let group=groups.find(c=>c.id===a.categoryId);if(!group){const name=o.category(a);group=groups.find(c=>c.name===name);if(!group){group={name,actions:[]};groups.push(group);}}group.actions.push(a);}
const colorText=c=>{const rgb=/^#([0-9a-f]{6})$/i.exec(c||'');if(!rgb)return '#20372e';const n=parseInt(rgb[1],16);return (((n>>16)&255)*299+((n>>8)&255)*587+(n&255)*114)/1000>145?'#18251f':'#ffffff';};
const choices=`<input type="hidden" id="slotAction" value="${esc(selected)}"><div class="slot-action-groups" role="group" aria-label="اختيار الفعل"><button type="button" class="slot-action-choice slot-action-empty" data-action-choice="" aria-pressed="${!selected}">بدون فعل</button>${groups.filter(g=>g.actions.length).map(g=>`<section class="slot-action-group"><h3>${g.color?`<i style="background:${esc(g.color)}"></i>`:''}${esc(g.name)}</h3><div class="slot-action-grid">${g.actions.map(a=>{const color=o.color?o.color(a):g.color||'#eff4ed';return `<button type="button" class="slot-action-choice" data-action-choice="${esc(a.id)}" aria-pressed="${a.id===selected}" style="background:${esc(color)};color:${colorText(color)}" title="${esc(a.description||a.name)}">${esc(a.name)}</button>`;}).join('')}</div></section>`).join('')}</div>`;
o.root.innerHTML=`<div class="slot-editor"><div class="dialog-head"><h2>${o.bulk?'تسجيل عدة خانات':'الفعل والملاحظة'}</h2><button id="close" type="button" aria-label="إغلاق">×</button></div><form id="slotForm">${o.bulk?`<div class="range-fields"><label>من<select id="slotFrom">${options(first,last-1,o.start)}</select></label><label>إلى<select id="slotTo">${options(first+1,last,o.end)}</select></label><label>التسجيل<select id="slotKind"><option value="actual" ${o.kind==='actual'?'selected':''}>ما فعلته</option><option value="planned" ${o.kind==='planned'?'selected':''}>المطلوب</option></select></label></div><p id="slotCount" class="hint" role="status"></p>`:`<input type="hidden" id="slotFrom" value="${o.start}"><input type="hidden" id="slotTo" value="${o.end}"><input type="hidden" id="slotKind" value="${o.kind}"><p class="hint">${o.kind==='actual'?'ما فعلته':'المطلوب'} · ${esc(o.time(o.start))} – ${esc(o.time(o.end))}</p><span id="slotCount" hidden></span>`}${choices}<p id="slotActionHint" class="hint"></p><label class="slot-field">ملاحظة<textarea id="slotNote" maxlength="1000" rows="3" placeholder="اكتب ملاحظة لهذه الخانة أو الفترة…">${esc(o.note||'')}</textarea></label><p class="hint">${o.bulk?'نفس الفعل والملاحظة لكل الخانات من البداية حتى وقت النهاية. الحفظ يستبدل التسجيل في الجزء المختار فقط.':'اختر الفعل وأضف ملاحظة ثم احفظ التسجيل.'}</p><p id="slotError" role="alert"></p><div class="slot-editor-actions"><button class="primary btn" type="submit">حفظ التسجيل</button><button id="clearSlot" class="secondary btn" type="button">إفراغ الفعل والملاحظة</button></div></form></div>`;
q('#slotFrom').value=String(o.start);q('#slotTo').value=String(o.end);q('#slotKind').value=o.kind;q('#slotAction').value=selected;q('#slotNote').value=o.note||'';o.root.onkeydown=e=>{if(e.key==='Escape')o.close();};
const refresh=()=>{let s=+q('#slotFrom').value,e=+q('#slotTo').value;try{validate(s,e,first);q('#slotCount').textContent=`${e-s} خانة · ${(e-s)*15} دقيقة`;q('#slotError').textContent='';}catch(err){q('#slotCount').textContent='';q('#slotError').textContent=err.message;}o.root.querySelectorAll?.('[data-action-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.actionChoice===q('#slotAction').value)));let a=o.actions.find(a=>a.id===q('#slotAction').value);q('#slotActionHint').textContent=a?.description||'';};
q('#slotFrom').onchange=q('#slotTo').onchange=q('#slotAction').onchange=refresh;o.root.querySelectorAll?.('[data-action-choice]').forEach(b=>b.onclick=()=>{q('#slotAction').value=b.dataset.actionChoice;refresh();});
q('#slotKind').onchange=()=>{if(!o.bulk){let v=o.read(+q('#slotFrom').value,q('#slotKind').value);q('#slotAction').value=v.action||'';q('#slotNote').value=v.note||'';}refresh();};
const commit=clear=>{try{let s=+q('#slotFrom').value,e=+q('#slotTo').value;validate(s,e,first);o.commit(s,e,q('#slotKind').value,clear?null:q('#slotAction').value,clear?'':q('#slotNote').value);o.close();}catch(err){q('#slotError').textContent=err.message;}};
q('#slotForm').onsubmit=e=>{e.preventDefault();commit(false);};q('#clearSlot').onclick=()=>commit(true);q('#close').onclick=o.close;refresh();if(o.show)o.show();
}
return{apply,validate,open};})();
