/* Firebase Authentication + per-account Realtime Database snapshots.
   Account-scoped local queues survive offline reloads. Transactions compare
   revisions so concurrent edits require an explicit user choice. */
(()=>{
const config={apiKey:'AIzaSyD8jxpVrvicStETloL8tk5s865dmNatIqE',authDomain:'mazen-productivity-bab1c.firebaseapp.com',databaseURL:'https://mazen-productivity-bab1c-default-rtdb.firebaseio.com',projectId:'mazen-productivity-bab1c',storageBucket:'mazen-productivity-bab1c.firebasestorage.app',messagingSenderId:'388570583199',appId:'1:388570583199:web:d62a7ad37c9330e22252aa'};
let auth,db,user=null,recordRef=null,unsubscribe=null,connectionRef=null,connectionHandler=null;
let baseRevision=0,dirty=false,ready=false,online=false,writing=false,applying=false,remote=null,timer=null,epoch=0,authReady=false;
let status='جاري تهيئة الحساب…',error='',mode='login',busy=false,editSequence=0,conflict=false;
const cacheKey=id=>'waqti-account-'+id;
function fresh(){return {...structuredClone(defaults),location:{...cairoLocation},method:'Egyptian',offsets:[0,0,0,0,0],hijriOffset:0,sunsetDays:{}}}
function readGuest(){try{let s=JSON.parse(localStorage.getItem('waqti-v1'));validate(s);return s}catch{return fresh()}}
function persist(){try{if(user)localStorage.setItem(cacheKey(user.uid),JSON.stringify({state,baseRevision,dirty}));else localStorage.setItem('waqti-v1',JSON.stringify(state));return true}catch{error='تعذر الحفظ على الجهاز. صدّر نسخة احتياطية الآن.';badge();return false}}
function apply(s){validate(s);applying=true;try{state=structuredClone(s);prayerCache.clear();setupCalendar();if(followToday){date=activeDay();prayer=currentPrayer();}lastActiveDay=activeDay();lastCivilDay=zonedDate();$('#picker').close();$('#prayerDialog').close();render()}finally{applying=false}}
function badge(){const el=$('#syncStatus');if(el){el.textContent=error?'⚠ '+error:status;el.title=el.textContent}const b=$('#accountButton');if(b)b.textContent=user?'الحساب والمزامنة':'دخول / إنشاء حساب'}
function report(message){status=message;badge();if(view==='account')renderAccount()}
function message(e){const c=e?.code||'';if(/permission.denied|PERMISSION_DENIED/i.test(c+' '+e?.message))return 'المزامنة ممنوعة: انشر قواعد Realtime Database الصحيحة.';return ({'auth/operation-not-allowed':'فعّل Email/Password من Authentication في Firebase.','auth/email-already-in-use':'هذا الإيميل مسجل بالفعل. استخدم تسجيل الدخول.','auth/invalid-email':'اكتب إيميلًا صحيحًا.','auth/weak-password':'كلمة المرور ضعيفة؛ استخدم ٨ أحرف أو أكثر.','auth/password-does-not-meet-requirements':'كلمة المرور لا توافق سياسة المشروع. استخدم أحرفًا كبيرة وصغيرة وأرقامًا ورمزًا.','auth/invalid-credential':'الإيميل أو كلمة المرور غير صحيحين.','auth/wrong-password':'الإيميل أو كلمة المرور غير صحيحين.','auth/user-not-found':'الإيميل أو كلمة المرور غير صحيحين.','auth/too-many-requests':'محاولات كثيرة. انتظر قليلًا ثم حاول مجددًا.','auth/network-request-failed':'تعذر الاتصال. راجع الإنترنت وحاول مجددًا.','auth/unauthorized-domain':'أضف نطاق التطبيق إلى Authorized domains في Firebase.','auth/invalid-api-key':'راجع إعدادات Firebase ومفتاح التطبيق.','auth/user-disabled':'هذا الحساب معطّل.'})[c]||'تعذر إكمال العملية. راجع الاتصال وإعدادات Firebase.'}
function decode(r){if(!r)return null;if(!Number.isInteger(r.revision)||r.revision<1||typeof r.payload!=='string')throw Error('bad record');let s=JSON.parse(r.payload);validate(s);return s}
function receive(r){remote=r;ready=true;$('#app').inert=false;let rev=r?.revision||0;
 if(writing)return;
 if(dirty){if(rev!==baseRevision){conflict=true;report('توجد نسختان مختلفتان؛ اختر من الحساب والمزامنة.');return}error='';report(online?'جاري المزامنة…':'محفوظ محليًا؛ في انتظار الاتصال');schedule();return}
 try{let s=decode(r);baseRevision=rev;conflict=false;error='';apply(s||fresh());persist();report(online?'● تمت المزامنة':'نسخة الحساب محفوظة على الجهاز')}catch{error='تعذر قراءة نسخة الحساب. احتفظ بنسختك المحلية وراجع ملف البيانات.';badge();if(view==='account')renderAccount()}
}
function schedule(){clearTimeout(timer);if(user&&ready&&dirty&&!conflict&&online&&!writing)timer=setTimeout(flush,500)}
async function flush(){if(!user||!ready||!dirty||conflict||!online||writing)return false;const ticket=epoch,uid=user.uid,ref=recordRef,expected=baseRevision,sequence=editSequence,payload=JSON.stringify(state);if(payload.length>4000000){error='البيانات تجاوزت حد المزامنة (٤ ملايين حرف). صدّر نسخة احتياطية.';badge();return false}writing=true;error='';report('جاري المزامنة…');try{
 const result=await ref.transaction(current=>{if((current?.revision||0)!==expected)return;return {payload,revision:expected+1,updatedAt:firebase.database.ServerValue.TIMESTAMP}},undefined,false);
 if(ticket!==epoch||user?.uid!==uid)return false;
 writing=false;
 if(!result.committed){remote=result.snapshot.val();conflict=true;report('تعديل من جهاز آخر؛ اختر النسخة التي تريد الاحتفاظ بها.');return false}
 baseRevision=result.snapshot.val().revision;dirty=sequence!==editSequence;persist();let latest=remote;
 if(latest&&(latest.revision||0)>baseRevision){receive(latest)}else{report(dirty?'جاري حفظ تعديلاتك الأخيرة…':'● تمت المزامنة');schedule()}
 return true;
 }catch(e){if(ticket===epoch){writing=false;error=message(e);persist();badge();if(view==='account')renderAccount()}return false}
}
function changed(){if(applying)return;if(user){dirty=true;editSequence++;persist();report(conflict?'يوجد تعارض؛ اختر نسخة من الحساب والمزامنة':online?'جاري المزامنة…':'محفوظ محليًا؛ في انتظار الاتصال');schedule()}else{persist();report('● محفوظ على هذا الجهاز — دون حساب')}}
function attach(u){epoch++;clearTimeout(timer);if(unsubscribe)unsubscribe();if(connectionRef&&connectionHandler)connectionRef.off('value',connectionHandler);unsubscribe=null;recordRef=null;connectionRef=null;connectionHandler=null;user=u;baseRevision=0;dirty=false;ready=false;writing=false;online=false;conflict=false;remote=null;error='';authReady=true;editSequence=0;
 if(!u){apply(readGuest());$('#app').inert=false;report('● محفوظ على هذا الجهاز — دون حساب');return}
 let cached=null;try{cached=JSON.parse(localStorage.getItem(cacheKey(u.uid)));if(cached){validate(cached.state);if(!Number.isInteger(cached.baseRevision)||cached.baseRevision<0)throw Error();baseRevision=cached.baseRevision;dirty=!!cached.dirty}}catch{cached=null;baseRevision=0;dirty=false}
 apply(cached?.state||fresh());report('جاري تحميل بيانات الحساب…');
 const ticket=epoch;recordRef=db.ref('waqti/users/'+u.uid);
 let handler=snap=>{if(ticket===epoch)receive(snap.val())};recordRef.on('value',handler,e=>{if(ticket!==epoch)return;$('#app').inert=false;error=message(e);badge();if(view==='account')renderAccount()});const attached=recordRef;unsubscribe=()=>attached.off('value',handler);
 connectionRef=db.ref('.info/connected');connectionHandler=snap=>{if(ticket!==epoch)return;online=snap.val()===true;if(online){if(ready){if(!dirty&&!conflict)report('● تمت المزامنة');schedule()}}else{report(dirty?'محفوظ محليًا؛ في انتظار الاتصال':'غير متصل — نسخة الحساب على الجهاز')}};connectionRef.on('value',connectionHandler);
}
function backupCurrent(){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download='waqti-before-conflict-'+date+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function renderAccount(){
 app.innerHTML=`<h1>الحساب والمزامنة</h1><p>نفس يومك ومهامك على أجهزتك، بإيميل وباسورد.</p><section class="panel"><p class="sync-message" role="status">${esc(error||status)}</p>${!user?`<div class="auth-tabs"><button id="loginMode" class="${mode==='login'?'primary':'secondary'}">تسجيل الدخول</button><button id="registerMode" class="${mode==='register'?'primary':'secondary'}">إنشاء حساب</button></div><form id="authForm" class="auth-form"><label class="field">الإيميل<input name="email" type="email" autocomplete="email" dir="ltr" required placeholder="name@example.com"></label><label class="field">كلمة المرور<input name="password" type="password" autocomplete="${mode==='register'?'new-password':'current-password'}" ${mode==='register'?'minlength="8"':''} required dir="ltr"></label>${mode==='register'?'<label class="field">تأكيد كلمة المرور<input name="confirmPassword" type="password" autocomplete="new-password" minlength="8" required dir="ltr"></label>':''}<button class="primary" ${busy||!authReady?'disabled':''}>${busy?'جاري التنفيذ…':mode==='register'?'إنشاء الحساب':'دخول'}</button><button type="button" id="resetPassword" class="secondary" ${busy||!authReady?'disabled':''}>نسيت كلمة المرور</button><p id="authFeedback" role="status"></p></form><p class="hint">بياناتك الحالية تظل على الجهاز. بعد الدخول يمكنك نقلها إلى حسابك من هنا.</p>`:`<h2 dir="ltr" style="overflow-wrap:anywhere">${esc(user.email||'')}</h2><p>تسجيل الدخول محفوظ على هذا المتصفح. كلمة المرور تُدار بواسطة Firebase Authentication ولا تُحفظ داخل بياناتك.</p>${conflict?'<div class="conflict-box"><h2>هناك تعديل مختلف من جهاز آخر</h2><p>يمكنك تنزيل النسخة الحالية قبل اختيار نسخة واحدة للمزامنة.</p><button id="backupConflict" class="secondary">تنزيل نسختي الحالية</button><button id="useCloud" class="primary">استخدام نسخة الحساب</button><button id="useLocal" class="secondary">اعتماد نسختي الحالية</button></div>':''}<div class="form"><button id="retrySync" class="primary">إعادة الاتصال والمزامنة</button><button id="importGuest" class="secondary" ${!ready||writing?'disabled':''}>نقل بيانات الجهاز السابقة للحساب</button><button id="logout" class="secondary" ${writing?'disabled':''}>تسجيل الخروج</button></div><p class="hint">نقل بيانات الجهاز يستبدل محتوى الحساب بعد تأكيدك. التعديلات غير المرسلة تبقى محفوظة لهذا الحساب على هذا الجهاز.</p>`}</section><section class="panel"><h2>تشغيل المزامنة لأول مرة</h2><p>فعّل Email/Password في Firebase Authentication، وانشر قواعد Realtime Database المرفقة. كل حساب يصل إلى بياناته فقط.</p></section>`;
 if(!user){$('#loginMode').onclick=()=>{mode='login';renderAccount()};$('#registerMode').onclick=()=>{mode='register';renderAccount()};$('#authForm').onsubmit=async e=>{e.preventDefault();if(busy||!authReady)return;let f=e.target.elements,email=f.email.value.trim(),password=f.password.value;if(mode==='register'&&password!==f.confirmPassword.value){$('#authFeedback').textContent='كلمتا المرور غير متطابقتين';return}busy=true;error='';const buttons=e.target.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);if(mode==='register')await auth.createUserWithEmailAndPassword(email,password);else await auth.signInWithEmailAndPassword(email,password);toast('تم تسجيل الدخول')}catch(e){error=message(e);badge();const feedback=$('#authFeedback');if(feedback)feedback.textContent=error}finally{busy=false;buttons.forEach(b=>b.disabled=false)}};
 $('#resetPassword').onclick=async()=>{const email=$('#authForm').elements.email.value.trim();if(!email){$('#authFeedback').textContent='اكتب الإيميل أولًا';return}if(busy)return;busy=true;$('#resetPassword').disabled=true;try{await auth.sendPasswordResetEmail(email);$('#authFeedback').textContent='إذا كان الإيميل مسجلًا، ستصلك رسالة لإعادة تعيين كلمة المرور.'}catch(e){$('#authFeedback').textContent=message(e)}finally{busy=false;const b=$('#resetPassword');if(b)b.disabled=false}};
 }else{
 $('#logout').onclick=async()=>{if(writing)return;if(dirty&&!confirm('توجد تعديلات لم تُزامن. ستظل محفوظة لهذا الحساب على الجهاز لتُرسل عند الدخول مجددًا. تسجيل الخروج؟'))return;try{await auth.signOut()}catch(e){error=message(e);badge()}};
 $('#retrySync').onclick=()=>{if(writing)return;persist();attach(auth.currentUser)};
 $('#importGuest').onclick=()=>{if(!ready||writing)return;if(!confirm('نقل بيانات الجهاز السابقة واستبدال بيانات هذا الحساب بها؟ يمكنك تصدير نسخة من الإعدادات أولًا.'))return;const guest=readGuest();apply(guest);changed();renderAccount()};
 if(conflict){$('#backupConflict').onclick=backupCurrent;$('#useCloud').onclick=()=>{if(!confirm('استخدام نسخة الحساب بدل تعديلات هذا الجهاز؟'))return;try{const s=decode(remote)||fresh();dirty=false;conflict=false;baseRevision=remote?.revision||0;apply(s);persist();report('● تم استخدام نسخة الحساب')}catch{error='نسخة الحساب غير صالحة';badge()}};$('#useLocal').onclick=()=>{if(!confirm('اعتماد نسخة هذا الجهاز بدل نسخة الحساب؟'))return;baseRevision=remote?.revision||0;conflict=false;dirty=true;persist();report('جاري المزامنة…');schedule()}}
 }
}
window.WaqtiSync={changed,renderAccount};$('#accountButton').onclick=()=>{view='account';render()};
try{firebase.initializeApp(config);auth=firebase.auth();auth.languageCode='ar';db=firebase.database();auth.onAuthStateChanged(attach,e=>{error=message(e);badge()});}catch(e){error='تعذر تشغيل Firebase. حدّث الصفحة وحاول مجددًا.';badge()}
window.addEventListener('online',schedule);window.addEventListener('beforeunload',e=>{if(dirty){persist();e.preventDefault();e.returnValue=''}});badge();
})();
